spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task_fork
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.coyoapp.tinytask: DEBUG
 
server:
  port: 8888